# Generated by Django 5.0.4 on 2026-09-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='alt_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
